### ISSUE TITLE
'npm run test' fails on new app

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#112]
Reproduce:
```
preact create app
cd app/
npm run test
```

```
> app@1.0.0 test /home/oren/app
> eslint src && preact test

The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

/home/oren/app/src/components/app.js
  11:2  error  Expected line before comment  lines-around-comment

/home/oren/app/src/components/header/index.js
  5:16  warning  Component should be written as a pure function  react/prefer-stateless-function

/home/oren/app/src/routes/home/index.js
  4:16  warning  Component should be written as a pure function  react/prefer-stateless-function

✖ 3 problems (1 error, 2 warnings)


npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 test: `eslint src && preact test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 test script 'eslint src && preact test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src && preact test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oren/.npm/_logs/2017-06-12T00_55_36_627Z-debug.log
```

* npm 4.2.0
* node v7.10.0
* Ubuntu 16.04.2 LTS

**Comment by oren** [comment]
surprisingly, now I am getting a different error when I am following the steps to reproduce:
```
eslint-config-synacor:
        ESLint configuration is invalid:
        - Unexpected top-level property "sourceType".

Referenced from: /home/oren/app/package.json
Error: eslint-config-synacor:
        ESLint configuration is invalid:
        - Unexpected top-level property "sourceType".

Referenced from: /home/oren/app/package.json
    at validateConfigSchema (/home/oren/app/node_modules/eslint/lib/config/config-validator.js:187:15)
    at Object.validate (/home/oren/app/node_modules/eslint/lib/config/config-validator.js:200:5)
    at load (/home/oren/app/node_modules/eslint/lib/config/config-file.js:550:19)
    at configExtends.reduceRight (/home/oren/app/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/home/oren/app/node_modules/eslint/lib/config/config-file.js:405:28)
    at Object.load (/home/oren/app/node_modules/eslint/lib/config/config-file.js:557:22)
    at loadConfig (/home/oren/app/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/home/oren/app/node_modules/eslint/lib/config.js:123:29)
    at Config.getConfig (/home/oren/app/node_modules/eslint/lib/config.js:262:26)

npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 test: `eslint src && preact test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 test script 'eslint src && preact test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src && preact test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oren/.npm/_logs/2017-06-12T01_57_28_451Z-debug.log
```

**Comment by developit** [comment]
Seems like an ESLint version mismatch.

**Comment by oren** [comment]
is it something that I should tweak?

**Comment by abs-zero** [comment]
I am getting this running eslint from `node_modules`, too
```
eslint-config-synacor:
        ESLint configuration is invalid:
        - Unexpected top-level property "sourceType".

Referenced from: /home/absolutezero/Documents/Projects/summer-routine/package.json
Error: eslint-config-synacor:
        ESLint configuration is invalid:
        - Unexpected top-level property "sourceType".

Referenced from: /home/absolutezero/Documents/Projects/summer-routine/package.json
    at validateConfigSchema (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config/config-validator.js:187
:15)
    at Object.validate (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config/config-validator.js:200:5)
    at load (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config/config-file.js:550:19)
    at configExtends.reduceRight (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config/config-file.js:421
:36)
    at Array.reduceRight (native)
    at applyExtends (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config/config-file.js:405:28)
    at Object.load (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config/config-file.js:557:22)
    at loadConfig (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config.js:123:29)
    at Config.getConfig (/home/absolutezero/Documents/Projects/summer-routine/node_modules/eslint/lib/config.js:262:26)
```

**Comment by Ninerian** [comment]
This is an error caused by the 4.0 update of eslint. A pull request in synacor/eslint-config-synacor fixes this. Until then, we should downgrade eslint to 3.9 or patch the file locally.

**Comment by developit** [comment]
Just released [eslint-config-synacor@1.0.1](https://github.com/synacor/eslint-config-synacor/releases/tag/1.0.1) with the fix.  Run `npm update` and it should be fixed! :)

**Comment by oren** [comment]
I just tried `npm run test` on a new app and I get the same exact error as my first message on this issue.

**Comment by developit** [comment]
Run `npm update` in the project, you will get the new config.

**Comment by oren** [comment]
Thanks! 
Works now but I still see the following:
```
npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 test: `eslint src && preact test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 test script 'eslint src && preact test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src && preact test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oren/.npm/_logs/2017-07-02T05_58_47_809Z-debug.log
~/app v /home/oren/.npm/_logs/2017-07-02T05_58_47_809Z-debug.log
~/app v /home/oren/.npm/_logs/2017-07-02T05_58_47_809Z-debug.log
```
And here is the content of the log file - http://paste.ubuntu.com/25001821/

I believe it's something to do with my OS (Ubuntu 16.04.2 LTS) but I am not sure. If anyone else see this error, please let me know!

**Comment by oren** [comment]
actually the test don't pass:
```
> app@1.0.0 test /home/oren/app
> eslint src && preact test

The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

/home/oren/app/src/components/app.js
  11:2  error  Expected line before comment  lines-around-comment

/home/oren/app/src/components/header/index.js
  5:16  warning  Component should be written as a pure function  react/prefer-stateless-function

/home/oren/app/src/routes/home/index.js
  4:16  warning  Component should be written as a pure function  react/prefer-stateless-function

/home/oren/app/src/routes/profile/index.js
  22:2  error  updateTime should be placed before componentDidMount  react/sort-comp

✖ 4 problems (2 errors, 2 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

```

**Comment by thangngoc89** [comment]
@oren It's just linitng issue. If you want to lint test to pass, fix the above issues. 
If you're unfamiliar with eslint/don't want to do the linting manually, try prettier

**Comment by developit** [comment]
We should fix any line errors in the default apps though, that's my fault for just dumping them in there. I will open a PR to adjust the lint setup so it lints `examples/**/*.js`.

**Comment by reznord** [comment]
I will do it right now
